# Generated by Django 5.2.11 on 2026-02-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('published_year', models.IntegerField()),
                ('available_copies', models.PositiveIntegerField()),
                ('authors', models.ManyToManyField(to='authors.author')),
            ],
        ),
    ]
